### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by jdcrecur** [vonheim/node-auto-rotate#1]
Hey there, great module! Have been search high and low for one just like this that works!

I get an error though when i try to run it against an image, although I am not sure if i am doing something wrong.

This is the snippet of code i am running (from your readme).

```
var rotator = require('auto-rotate');
var file = '/var/node/mysite/app/routes/logged_in/dev_api/test_image.jpeg';
var file2 = '/var/node/mysite/app/routes/logged_in/dev_api/test_image2.jpeg';
rotator.autoRotateFile( file, file2)
  .then(function() {
    console.log("File rotated ok");
  }).catch(function(err) {
    console.error("Got error: "+err);
  });
```

This is the error:

```
Error: /var/node/mysite/node_modules/auto-rotate/node_modules/lwip/build/Release/lwip_image.node: invalid ELF header
        server-0 (err):     at Error (native)
        server-0 (err):     at Module.load (module.js:355:32)
        server-0 (err):     at Function.Module._load (module.js:310:12)
        server-0 (err):     at Module.require (module.js:365:17)
        server-0 (err):     at require (module.js:384:17)
        server-0 (err):     at /var/node/mysite/node_modules/auto-rotate/node_modules/lwip/lib/Image.js:3:22
        server-0 (err):     at Object.<anonymous> (/var/node/mysite/node_modules/auto-rotate/node_modules/lwip/lib/Image.js:15:3)
        server-0 (err):     at Module._compile (module.js:460:26)
        server-0 (err):     at Object.Module._extensions..js (module.js:478:10)
        server-0 (err):     at Module.load (module.js:355:32)
        server-0 (err):     at Function.Module._load (module.js:310:12)
        server-0 (err):     at Module.require (module.js:365:17)
        server-0 (err):     at require (module.js:384:17)
        server-0 (err):     at /var/node/mysite/node_modules/auto-rotate/node_modules/lwip/lib/ImagePrototypeInit.js:3:17
        server-0 (err):     at Object.<anonymous> (/var/node/mysite/node_modules/auto-rotate/node_modules/lwip/lib/ImagePrototypeInit.js:606:3)
        server-0 (err):     at Module._compile (module.js:460:26)
```

**Comment by vonheim** [comment]
@johnc1984: Looks like a problem with the LWIP module. Do you remember if you got any error messages when you installed it?
Maybe you can try to remove the node_modules directory, and rerun "npm install".

**Comment by jdcrecur** [comment]
@vonheim Yes, it was the lwip module that was the cause of the error, it did not complain when it was being installed, only when being run. Eitherway this is not your module that is at fault so will close this issue.

Cheers,
J
